### PR TITLE
Remove MBEDTLS_ENTROPY_NV_SEED, MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES and MBEDTLS_PSA_INJECT_ENTROPY

### PR DESCRIPTION
**Pull request by urutva**
Following changes are done,

1. Remove MBEDTLS_NO_DEFAULT_ENTROPY_SOURCES config option to utilize
    Hardware TRNG available on K64F
2. Remove MBEDTLS_ENTROPY_NV_SEED config option and relevant method
    fake_set_initial_nvseed() used to inject fake NV seed
3. Remove static private and public key and let attestation service
    generate them
4. Remove configuration MBEDTLS_PSA_INJECT_ENTROPY from the example.
    The attestation example need NOT inject entropy. The PSA Crypto service
    will inject the entropy based on configuration in secure world and
    availability of hardware
5. Remove the paragraph "Factory injection of entropy" from README.md to
    reflect the removal of "fake_set_initial_nvseed" method from code
6. Let the master branch of attestation example follow the master branch of
    mbed-os

### CODE REVIEW

**Comment by urutva** [comment]
@Patater @jainvikas8 Please review

**Review by Patater — APPROVED** [review]
LGTM

**Comment by Patater** [comment]
Tested working on K64F

**Review by jainvikas8 — APPROVED** [review]
Looks fine to me.

**Pull request merged**
